# Redirect Gradle build cache to D: to avoid eating C: drive
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx1g -XX:+UseG1GC
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=34
